# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treebuilder', '0002_auto_20161203_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_marriage', models.DateField(blank=True, null=True)),
                ('date_of_divorce', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='marriage',
            name='spouse1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriage_spouse1', to='treebuilder.Person'),
        ),
        migrations.AddField(
            model_name='marriage',
            name='spouse2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriage_spouse2', to='treebuilder.Person'),
        ),
    ]
